name: french-solitaire
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - marimo
  - mcp
  - duckdb
  - sqlglot
  - altair
  - vegafusion
  - vl-convert-python
  - ruff
  - openai
  - nbformat
  - websockets
  - python-lsp-server
  - pip
  - gymnasium
  - mlflow
  - matplotlib
  - tensorboard
  - pytest
  - ty
  - basedpyright
  - huggingface-hub
